#require File.dirname(__FILE__) +  asf-soap-adapter convenience classes.

require File.dirname(__FILE__) + '/salesforce/file_writer.rb'
require File.dirname(__FILE__) + '/salesforce/sf_base.rb'
require File.dirname(__FILE__) + '/salesforce/account.rb'
require File.dirname(__FILE__) + '/salesforce/account_feed.rb'
require File.dirname(__FILE__) + '/salesforce/asset.rb'
require File.dirname(__FILE__) + '/salesforce/asset_feed.rb'
require File.dirname(__FILE__) + '/salesforce/campaign.rb'
require File.dirname(__FILE__) + '/salesforce/campaign_feed.rb'
require File.dirname(__FILE__) + '/salesforce/case.rb'
require File.dirname(__FILE__) + '/salesforce/case_feed.rb'
require File.dirname(__FILE__) + '/salesforce/chatter_feed.rb' ###
require File.dirname(__FILE__) + '/salesforce/contact.rb'
require File.dirname(__FILE__) + '/salesforce/contact_feed.rb'
require File.dirname(__FILE__) + '/salesforce/contract.rb'
require File.dirname(__FILE__) + '/salesforce/contract_feed.rb'
require File.dirname(__FILE__) + '/salesforce/entity_subscription.rb'
require File.dirname(__FILE__) + '/salesforce/feed_comment.rb'
require File.dirname(__FILE__) + '/salesforce/feed_post.rb'
require File.dirname(__FILE__) + '/salesforce/feed_tracked_change.rb'
require File.dirname(__FILE__) + '/salesforce/group.rb'
require File.dirname(__FILE__) + '/salesforce/lead.rb'
require File.dirname(__FILE__) + '/salesforce/lead_feed.rb'
require File.dirname(__FILE__) + '/salesforce/news_feed.rb'
require File.dirname(__FILE__) + '/salesforce/opportunity.rb'
require File.dirname(__FILE__) + '/salesforce/opportunity_feed.rb'
require File.dirname(__FILE__) + '/salesforce/product2.rb'
require File.dirname(__FILE__) + '/salesforce/product2_feed.rb'
require File.dirname(__FILE__) + '/salesforce/solution.rb'
require File.dirname(__FILE__) + '/salesforce/solution_feed.rb'
require File.dirname(__FILE__) + '/salesforce/user.rb'
require File.dirname(__FILE__) + '/salesforce/user_feed.rb'
require File.dirname(__FILE__) + '/salesforce/user_profile_feed.rb'
